mod binomial;
pub mod degree;
pub mod derivative;
pub mod integral;
pub mod monomial;
pub mod numerics;
pub mod poly_math;
pub mod polynomial;
pub mod sparsepolynomial;
mod strings;
pub mod traits;
pub mod trinomial;
