pub mod binomial;
pub mod derivative;
pub mod err;
pub mod integral;
pub mod monomial;
pub mod numerics;
pub mod poly_math;
pub mod polynomial;
pub(crate) mod roots;
pub mod sparsepolynomial;
mod strings;
pub mod terms;
pub mod traits;
pub mod trinomial;
